### ISSUE TITLE
[BUG]: Setup failed after upgrade to 0.34.6

### ISSUE THREAD

**Issue by jdgarcia99** [plugwise/plugwise-beta#351]
### Describe the bug.

After upgrade to v.34.6 cannot load plug wise component.

The log shows error:

Setup failed for custom integration plugwise: Unable to import component: cannot import name 'EntityCategory' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

I upgraded today to version 0.34.7 but the error is still there

### What version of Home Assistant Core has the issue?

2023.2.5

### What was the last working version of Home Assistant Core?

2023.2.5

### What type of installation are you running?

Home Assistant Supervised

### How did you install plugwise-beta?

HACS

### What kind of Plugwise device is having issues?

USB: Stick

### What firmware version is your Plugwise product at?

Firmware: 2011-06-27 10:52:18

**Comment by bouwew** [comment]
Ah Ok, please go back to the last working version: v0.34.5.
I was too early with this update, I guess this will work with HA version 2023.3.0.

**Comment by bouwew** [comment]
Corrected via #353 v0.34.7 should now be shown only for HA 2023.3.0 and up.

**Comment by jdgarcia99** [comment]
> Ah Ok, please go back to the last working version: v0.34.5.
> I was too early with this update, I guess this will work with HA version 2023.3.0.

Didn't work

Had to go to V0.34.3 to work again

**Comment by bouwew** [comment]
Ok, that's strange. Did you see the same error with v0.34.5? Or a different error?

**Comment by jdgarcia99** [comment]
> Ok, that's strange. Did you see the same error with v0.34.5? Or a different error?

Once installed the component in hacks, when trying to add a new integration within the settings -> integrations -> add integration, system gave me an error related to count' find a handler.

Sorry I did not catch the exact massage, but downgraded a little bit more

**Comment by bouwew** [comment]
You can use the Redownload option in HACS to roll back to an older version.
Using that option you should be able to downgrade (now upgrade) to v0.34.5

**Comment by CasparTheBridge** [comment]
I had the same issue, reverted back to v0.34.5 and now it is working fine again :)

**Comment by bouwew** [comment]
I have deleted the v0.34.7 release, and added the v0.34.7.1 release which has HA 2023.3.0 as the minimum required version.
Once you've upgraded to HA 2023.3.0 this new version will become visible in HACS.
