### ISSUE TITLE
After update to 0.12.0 I get Setup failed for plugwise: Unable to import component: cannot import name 'SIGNAL_STRENGTH_DECIBELS_MILLIWATT'

### ISSUE THREAD

**Issue by Geronimo2015** [plugwise/plugwise-beta#134]
After update to 0.12.0 I get:

Logger: homeassistant.setup
Source: setup.py:138
First occurred: 6:36:32 PM (1 occurrences)
Last logged: 6:36:32 PM

Setup failed for plugwise: Unable to import component: cannot import name 'SIGNAL_STRENGTH_DECIBELS_MILLIWATT' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)

Home assistant version: 0.116.4

**Comment by brefra** [comment]
Appearently the `SIGNAL_STRENGTH_DECIBELS_MILLIWATT` const has been [recently added](https://github.com/home-assistant/core/pull/40436) to HomeAssistant and is not available to version prio to 0.117, scheduled to be release this week.
@bouwew / @CoMPaTech should we revert this one, or make 0.117 the minimal HA version in `hacs.json`?

**Comment by brefra** [comment]
@Geronimo2015, We just release two new releases. 
The 0.12.1 release should prevent the reported issue and is available if you're running Home Assistant version 0.115 or 0.116.
The subsequent 0.12.2 version should only be available if you're running Home Assistant 0.117 or later.

**Comment by CoMPaTech** [comment]
@Geronimo2015 please also let us know if 12.2 shows up (I recall having HACS not checking minimal versions somewhere in the past). 

@brefra thanks!

**Comment by Geronimo2015** [comment]
Hi thanks it shows up but I get:

You are running Home Assistant version '0.116.4', but this repository
requires minimum version '0.117.0' to be installed.

**Comment by CoMPaTech** [comment]
You should be able to choose 'reinstall' on the HACS-integration page

<img width="562" alt="Schermafbeelding 2020-10-26 om 16 46 30" src="https://user-images.githubusercontent.com/5751088/97194783-d88e0f80-17aa-11eb-8f53-9ef5934809d2.png">

From there you will be able to pick the 12.1

<img width="866" alt="Schermafbeelding 2020-10-26 om 16 46 36" src="https://user-images.githubusercontent.com/5751088/97194777-d62bb580-17aa-11eb-9c98-84775e0dc0aa.png">

**Comment by Geronimo2015** [comment]
I tried but Install button is greyed out

[image: image.png]

**Comment by CoMPaTech** [comment]
@Geronimo2015 is it still not working for you (unfortunately your image didn't upload correctly)

**Comment by Geronimo2015** [comment]
No sorry, not yet:

` You are running Home Assistant version '0.116.4', but this repository
requires minimum version '0.116.99' to be installed.  `
when I select 0.12.1.
Install button is greyed out.

**Comment by CoMPaTech** [comment]
Thats weird, apparently it doesn't work as expected. It should do 116.99 for 0.12.3, not for 12.2:

12.2 = https://github.com/plugwise/plugwise-beta/blob/d961fa6fa089d436162c4195ae0474bfce061013/hacs.json

You should try installing 12.2 (< 117) or 12.3 (>117 coming released tomorrow)

It apparently does update (catching our 116.99) - does it also do this if you click the three dots on plugwise and then select 'update information'? (And last resort, if you restart HA it still won't budge?)

**Comment by Geronimo2015** [comment]
Nope, all did not help, I'll await 117

**Comment by Geronimo2015** [comment]
After update to 117 it installed correctly.

**Comment by CoMPaTech** [comment]
Tnx for the update - we'll have to check how/if/what HACS is doing to or with it then

**Comment by Geronimo2015** [comment]
The gas interval is somehow not working for my plugwise smile  2.1.13  .

sensor.p1_gas_consumed_interval
<https://jschoot.duckdns.org/developer-tools/state#> is always 0

cumulative is working though for gas, but all intervals are 0

**Comment by Geronimo2015** [comment]
can you please remove the url int the comment above?

**Comment by Geronimo2015** [comment]
Intervals for electricity are working I noticed now

**Comment by CoMPaTech** [comment]
Hi @Geronimo2015 gas interval still not working? 

Could you double-check the values are present in `http://{your_p1_address}/core/domain_objects`? If you search for gas_consumed there you should find something resembling the below.

```
                        <interval_log id='4e0d78a9862e49d68531920f4d913dce'>
                                <updated_date>2020-04-08T13:00:00+02:00</updated_date>
                                <type>gas_consumed</type>
                                <unit>m3</unit>
                                <last_consecutive_log_date>2020-04-08T12:00:00+02:00</last_consecutive_log_date>
                                <interval>PT1H</interval>
                                <period start_date="2020-04-08T13:00:00+02:00" end_date="2020-04-08T13:00:00+02:00" interval="PT1H">
                                        <measurement log_date="2020-04-08T13:00:00+02:00">0.00</measurement>
                                </period>
                                <gas_interval_meter id='d28cd8b90b7643e38ef01780b12b6b5c'/>
                        </interval_log>
```

**Comment by bouwew** [comment]
It could be that your energy-meter does not provide the gas-interval-value.

**Comment by Geronimo2015** [comment]
It is there:

<interval_log id="f9a135e273bb43a096ca0c54b266ccaa">
<unit>m3</unit>
<type>gas_consumed</type>
<last_consecutive_log_date>2020-06-12T16:00:00+02:00
</last_consecutive_log_date>
<updated_date>2020-06-12T16:00:00+02:00</updated_date>
<interval>PT1H</interval>
<period start_date="2016-02-28T09:00:00+01:00" end_date="
2020-06-12T16:00:00+02:00" interval="PT1H">
<measurement log_date="2020-06-12T16:00:00+02:00">0.000</measurement>
</period>
</interval_log>

**Comment by bouwew** [comment]
Yes, but that does not mean that the measurement is actually present in the output of the P1-port.

The XML-data that the Plugwise component reads from the Smiles (Adam, Anna, P1, Stretch) contains many parameters that we pass onto HA Core as binary_sensors/sensors. But we, the code-owners, don't know for sure whether these parameters are always meaningful for all the systems out there.

**Comment by Geronimo2015** [comment]
I tested and got result on http://
{plugwise.ip}/core/modules;id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:
So seems to be present.
Hope this helps.

<modules>
<module id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<vendor_name/>
<vendor_model/>
<hardware_version/>
<firmware_version/>
<created_date>2018-03-03T11:53:53.030+01:00</created_date>
<modified_date>2020-11-03T16:18:57.700+01:00</modified_date>
<deleted_date/>
<services>
<gas_interval_meter id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<measurement log_date="2020-11-03T15:00:00+01:00" unit="m3" interval="PT1H"
directionality="consumed">0.010</measurement>
</gas_interval_meter>
<gas_cumulative_meter id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<measurement log_date="2020-11-03T16:00:00+01:00" unit="m3" directionality="
consumed">8499.617</measurement>
</gas_cumulative_meter>
</services>
<protocols>
<dsmrgas id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<serial>xxxxxxxxxxxxxxxxxxxxxxxxx</serial>
<dsmrmain id="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"/>
</dsmrgas>
</protocols>
</module>
</modules>

**Comment by bouwew** [comment]
Which firmware is your P1 on?

And what do you see at /core/domain_objects? The same value as at /core/modules? Or a different value?

**Comment by Geronimo2015** [comment]
firmware  2.1.13

In domain objects gas interval is 0 and not up-to-date

....
<interval_log id="xxxxxxxxxxxxxxxxxxxxxxxxxxxx">
<unit>m3</unit>
<type>gas_consumed</type>
<last_consecutive_log_date>2020-06-12T16:00:00+02:00
</last_consecutive_log_date>
<updated_date>2020-06-12T16:00:00+02:00</updated_date>
<interval>PT1H</interval>
<period start_date="2016-02-28T09:00:00+01:00" end_date="
2020-06-12T16:00:00+02:00" interval="PT1H">
<measurement log_date="2020-06-12T16:00:00+02:00">0.000</measurement>
</period>
</interval_log>
....

**Comment by bouwew** [comment]
Ah Ok, that's a very old one, I have had two of these. Does your unit also show temporary drop-outs?
I got rid of mine due to these drop-outs happening frequently on both.

Can you please also check the value at /core/direct_objects? Is the value over there up-to-date?
If not, we might need to change to reading the data from /core/modules.

**Comment by Geronimo2015** [comment]
That is also 0  and out dated,
i don't have dropouts at least not noticed.

**Comment by Geronimo2015** [comment]
I found the problem,

my gas meter was configured incorrectly in smile settings.

now it works like it should.

Thanks for the help

**Comment by bouwew** [comment]
Ok great, that saves us some work :)

About the dropouts, I would notice them when looking at the history-graph of the `sensor.net_electricity_point`, I would see regular intervals where the result was zero for a short time. My P1's were connected via WiFi.
Do you see this as well? When not, is your P1 perhaps connected via an Ethernet cable?
